name: win_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  win_rust_fmt_auto_build_test:

    runs-on: windows-latest

    steps:
  
    - name: install Git for Windows
      run: choco install git.install

    - uses: 1arp/create-a-file-action@0.4.5
      with:
        path: c:\\Users\\runneradmin\\.ssh
        isAbsolutePath: true
        file: agent.env
        content: 

    - uses: 1arp/create-a-file-action@0.4.5
      with:
        path: c:\\Users\\runneradmin
        isAbsolutePath: true
        file: .bashrc
        content: |
          printf "  \033[33m Run ssh-agent and write SSH_AUTH_SOCK  \033[0m\n"
          SSH_ENV=~/.ssh/agent.env
          test -f "$SSH_ENV" && . "$SSH_ENV" | /dev/null ;
          # agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
          agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)
          if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
            printf "  \033[33m Starting ssh-agent as a windows process in the background... \033[0m\n"
            (umask 077; ssh-agent >| "$SSH_ENV")
            cat ~/.ssh/agent.env
            source "$SSH_ENV" 
          fi
          unset SSH_ENV

    - name:  "source ~/.bashrc"
      shell: bash
      run: source ~/.bashrc

    - name:  "echo $SSH_AUTH_SOCK"
      shell: bash
      run: echo "$SSH_AUTH_SOCK"

    - name:  "echo $SSH_AGENT_PID;"
      shell: bash
      run: echo "$SSH_AGENT_PID"

    - name:  "ssh-add -l"
      shell: bash
      run: ssh-add -l
