name: win_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  win_rust_fmt_auto_build_test:

    runs-on: windows-latest

    steps:
  
    - name: install Git for Windows
      run: choco install git.install

    - name:  "ssh-agent -s >~/.ssh/agent.env"
      shell: bash
      run: ssh-agent -s >~/.ssh/agent.env

    - name:  "source ~/.ssh/agent.env"
      shell: bash
      run: source ~/.ssh/agent.env

    - name:  "cat ~/.ssh/agent.env"
      shell: bash
      run: cat ~/.ssh/agent.env

    - name:  "echo $SSH_AUTH_SOCK"
      shell: bash
      run: echo "$SSH_AUTH_SOCK"

    - name:  "echo $SSH_AGENT_PID;"
      shell: bash
      run: echo "$SSH_AGENT_PID"

    - name:  "ssh-add -l"
      shell: bash
      run: ssh-add -l
